services:
  db:
    image: postgres:18-apine
    container_name: nic-test-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER:~postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:~postgres}
    ports:
    - 5432:5432
    volumes:
    - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:8-alpine
    container_name: nic-test-redis
    ports:
    - 6379:6379
    volumes:
    - redisdata:/data

volumes:
  pgdata:
  redisdata:
